### ISSUE TITLE
https problem with demo URL on gh-pages

### ISSUE THREAD

**Issue by Scarygami** [PolymerElements/iron-component-page#11]
Unfortunately github has the bad habit of redirecting *https*://name.github.io/my-element/components/my-element/demo to *http*://name.github.io/my-element/components/my-element/demo/ which results in the iframe not being loaded when accessing the gh pages via https.

This is really a github issue (and I will report it accordingly) but setting the `_demoUrl` to `demo/` instead of `demo` by default would also prevent this issue.

**Comment by atotic** [comment]
hydrolysis now defaults @demo to demo/index.html. That should fix it.
