### ISSUE TITLE
demoPath is not a property

### ISSUE THREAD

**Issue by drxcheng** [PolymerElements/iron-component-page#13]
in _updateDemoUrl, it checks this.demoPath, but it is not a public attribute, or it is not initialized anywhere. So _demoUrl will always be empty.

is this a bug?

How to specify demo view?

**Comment by atotic** [comment]
Demo view is specified with @demo jsdoc tag.
_demoUrl code should be removed?

**Comment by mbleigh** [comment]
Yeah it's coming out, already gone in the `polish` branch that I've been working on.
