### ISSUE TITLE
_activeChanged throws if null _activeElement, do not reference descriptor.

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-component-page#14]
If there is nothing to be parsed, _activeChanged throws because _activeElement is null, and it derefs this._activeElement.jsdoc.

Same code should not be referencing jsdoc. Demo elements are stored as descriptor.demos[], not inside jsdoc.

**Comment by mbleigh** [comment]
This has been addressed in `polish` branch -- first implementation was before `descriptor.demos` landed in hydrolysis.
