### ISSUE TITLE
How to avoid line breaks in the docs?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/iron-component-page#143]
### Description

I update the docs from:

![code-1](https://user-images.githubusercontent.com/1007051/28867129-54faa18e-7775-11e7-81e6-ef6647954925.jpg)

To: (line break in lines 264-265, to respect a `max-len` rule)

![code-2](https://user-images.githubusercontent.com/1007051/28867137-5798bb10-7775-11e7-8160-43b4c9efbbf9.jpg)

But it changes from:

![docs-1](https://user-images.githubusercontent.com/1007051/28866934-c3740f98-7774-11e7-861e-5b9b202ea8f6.jpg)

To:

![docs-2](https://user-images.githubusercontent.com/1007051/28866939-cdb36e72-7774-11e7-9253-15c42e0c3177.jpg)

How can I fix it? I don't want the line break in the docs.

**Comment by justinfagnani** [comment]
This seems like a markdown issue. I would look on how to wrap table cells, either in general markdown docs, or maybe here: https://github.com/chjj/marked
