### ISSUE TITLE
3.0 Preview doesn't render correctly on Firefox.

### ISSUE THREAD

**Issue by RebeccaStevens** [PolymerElements/iron-component-page#150]
### Description
iron-component-page 3.0 preview renders incorrectly on Firefox. It renders correctly on Chrome. I haven't tested any other browsers.

### Expected outcome

Renders the same as on chrome:
![chrome](https://user-images.githubusercontent.com/7224206/36293649-3b5ff528-1340-11e8-8ae3-04a6d11841d0.png)

### Actual outcome

Renders incorrectly:

- Header is not at the top of the page and does not take up the full width of the content container.
- Demo iframes do not fill the content container
- Incorrect font.

![firefox](https://user-images.githubusercontent.com/7224206/36293650-3e793d82-1340-11e8-86dd-96ef504c3fab.png)

### Live Demo
https://catalyst.github.io/CatalystElements/#/elements/catalyst-flip-button

### Steps to reproduce

1. Put an `iron-component-page` element in the page.
2. Open the page in Firefox.

### Browsers Affected
- [ ] Chrome 64
- [x] Firefox 58

**Comment by aomarks** [comment]
Thanks for the report! Have you seen the same thing with 2.x elements on Firefox?

**Comment by RebeccaStevens** [comment]
I've just tested with the latest release of this component (v3.0.1) with polymer 2.5.0 and everything works fine. It seems to just be an issue with the 3.0-preview branch using polymer 3 preview.

**Comment by RebeccaStevens** [comment]
After further testing, is seems that the issue was caused by ShadyCSS's [custom style interface](https://github.com/webcomponents/shadycss/blob/master/custom-style-interface.min.js) script. After removing this script, the page renders correctly on both Firefox and Chrome.
