### ISSUE TITLE
New base property causes _srcChanged() to be invoked before this.src is set

### ISSUE THREAD

**Issue by jeffposnick** [PolymerElements/iron-component-page#17]
https://github.com/PolymerElements/iron-component-page/commit/4bc8531de4d6ab9b919e52e7c4fbb8c15c749560 introduced a race condition in which the new `base` property causes the `_srcChanged()` observer to be called before the `src` property is set.

Inside `_srcChanged()`, the check for [`this.src`](https://github.com/PolymerElements/iron-component-page/blob/master/iron-component-page.html#L299) ends up being evaluated to `false` even if `src` is set on the element, since it hasn't been copied over to `this` yet.

This breaks doc pages when the `src` is meant to be something other than the parent directory's name with the `.html` suffix.

**Comment by atotic** [comment]
good one, working on it

**Comment by jeffposnick** [comment]
@atotic, the bug was re-added in https://github.com/PolymerElements/iron-component-page/commit/0f396063d95c7d36ef9acf943e9cd935a7ec04aa

Can you please cut a new release without using `_srcObserver` for `base`? Or find another way of achieving the same effect that doesn't have the same race condition?

This is preventing https://github.com/PolymerElements/platinum-sw from using the current release of `<iron-component-page>`. CC: @addyosmani @wibblymat

**Comment by atotic** [comment]
fixed again in 7e58148
