### ISSUE TITLE
Multiple demos not supported

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-component-page#20]
Need a UI when multiple demos are there.
<next demo> <previous demo>

**Comment by ckuiawa** [comment]
The documentation page supports multiple elements in the same directory. Based on that, I would expect multiple demos to work the same way.

**Comment by atotic** [comment]
Multiple demos are supported by hydrolysis, but not by iron-component-page

**Comment by ronnyroeller** [comment]
+1

**Comment by MeTaNoV** [comment]
any news on this one?

**Comment by atulkshirsagar** [comment]
+1

**Comment by aomarks** [comment]
The 3.0 version (on master and RC, stable release coming soon) has support for multiple demos.

![demos](https://user-images.githubusercontent.com/48894/27351411-2074f94e-55b2-11e7-8905-03cd9a5f6697.png)
