### ISSUE TITLE
Is this live somewhere?

### ISSUE THREAD

**Issue by dandv** [PolymerElements/iron-component-page#25]
If so, it would be nice to set the website of this GitHub repo to point to the live instance.

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

https://elements.polymer-project.org/elements maybe?

**Comment by ebidel** [comment]
Added
