### ISSUE TITLE
Core API navigation is confusing

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-component-page#29]
The drop-down menu in the core docs tends to obscure what's available. Would be much better to have a drawer panel with a menu of available packages/modules/whatever we call them.

The catalog probably wants to do something else here. iron-component-page probably has to support both these use cases (built-in navigation & external navigation).

**Comment by justinfagnani** [comment]
We need some UX help on this. @tjsavage ?

**Comment by tjsavage** [comment]
In the short-term it would be nice to do something like this:

![api reference](https://cloud.githubusercontent.com/assets/348551/13189690/b768c436-d70d-11e5-9340-dffaa8cdd1b2.png)

Longer-term we should roll this in with an updated polymer-project.org site.

**Comment by arthurevans** [comment]
:+1: A simple nav drawer instead of the pulldown would make this much more usable for the Polymer API docs. And, I think, more useable for people documenting their own elements. **Just this one change in the short term would be excellent.**

For the more general element use case, ideally we'd have some way of navigating both packages and individual elements--as currently designed, iron-component-page only really handles as single "bundle" of elements. The catalog adds some extra logic (but still doesn't nail the navigation IMO, because bundled elements aren't visible from the top level).

**Comment by arthurevans** [comment]
We just had another report on this. It would be really good to fix this. Can we just fix this?

**Comment by justinfagnani** [comment]
Working on this now. I'll put up a initial PR soon

**Comment by aomarks** [comment]
3.0 is published and it's got a side nav much like this.
