### ISSUE TITLE
Publishing for gh-pages

### ISSUE THREAD

**Issue by AaronLayton** [PolymerElements/iron-component-page#31]
I was following the instructions set out here
https://www.polymer-project.org/1.0/docs/start/reusableelements.html

and besides some other issues (https://github.com/Polymer/tools/issues/53) I did manage to manually follow the instructions in their `gp.sh` to push a gh-page branch with my demo.

However, there doesn't seem to be any `icon-component-page` that got sent to my gh-page aswell. My main question - is this something that this Repo needs to address, or is it part of the Tooling chain? How do I get my nice looking `iron-component-page` online with minimal fuss

**Comment by Scarygami** [comment]
Do you have a link to your demo repository?

You will have to have `iron-component-page` include in your bower.json dependencies, which is there if you started from [seed-element](https://github.com/PolymerElements/seed-element).

**Comment by ebidel** [comment]
Yep. https://github.com/Polymer/tools/commits/master/bin/gp.sh has added a bunch of 1.0 support. Namely, if you list `iron-component-page` in `devDependencies`, it will be pulled in now. The `demo` folder will also be pulled in and uploaded to gh-pages.

**Comment by jahglow** [comment]
Actually I have the same issue at [jahglow.github.io/radial-gauge/](jahglow.github.io/radial-gauge/): My bower.json is:
`  "name": "radial-gauge",
  "version": "1.0.1",
  "authors": [
    "John Archer <jahglow@gmail.com>"
  ],
  "description": "Animated radial gauge with up to double rails",
  "keywords": [
    "web-component",
    "polymer"
  ],
  "main": "radial-gauge.html",
  "license": "http://polymer.github.io/LICENSE.txt",
  "homepage": "https://github.com/jahglow/radial-gauge/",
  "ignore": [
    "/.*",
    "/test/"
  ],
  "dependencies": {
    "polymer": "Polymer/polymer#^1.0.0",
    "iron-icons": "PolymerElements/iron-icons#1.0.0",
    "neon-animation": "PolymerElements/neon-animation#1.0.0",
    "paper-styles": "PolymerElements/paper-styles#1.0.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#^1.0.0",
    "transform-animation-multiple": "jahglow/transform-animation-multiple"
  },
  "devDependencies": {
    "iron-component-page": "PolymerElements/iron-component-page#^1.0.0",
    "web-component-tester": "*",
    "paper-card": "PolymerElements/paper-card#^1.1.0"
  },
  "resolutions": {
    "paper-styles": "^1.1.0",
    "paper-card": "^1.1.0"
  }
}`

Though as you see in the console if you follow to the repo link, the webcomponents-lite.min.js and the  `icon-component-page` are missing at the root (jahglow.github.io/)
