### ISSUE TITLE
hidden$="[[_activeDescriptor]]" causes JSON serialization error 

### ISSUE THREAD

**Issue by atotic** [PolymerElements/iron-component-page#33]
_activeDescriptor is a big doc, and a circular structure. Trying to JSON.serialize(_activeDescriptor) throws "TypeError: Converting circular structure to JSON"

It is very sensible to bind it to a hidden attribute.

It is not sensible for Polymer to serialize _activeDescriptor just to set a boolean.

**Comment by notwaldorf** [comment]
Right now the solution is to make a computed function that casts the object to a boolean.

**Comment by justinfagnani** [comment]
@atotic I know this is old, but do you have an example I can reproduce this on?

**Comment by atotic** [comment]
Dang, this is old, I forget where I encountered it in the wild. To reproduce, create a cyclical object:
```
var  x = {};
x.cycle = x;
JSON.stringify(x) will throw cyclic object value error.
```
Then, bind x to a boolean value. I think this should work:
```
<input hidden$="{{x}}">
```
and you'll get the error.
