### ISSUE TITLE
Support multiple sources

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-component-page#34]
Elements that are not imported by another element are not picked up by the system:

![screen shot 2015-06-17 at 8 31 52 am](https://cloud.githubusercontent.com/assets/238208/8211354/5db9e0e6-14cb-11e5-811a-bee3786dd1c4.png)

The component page does not include all of the elements:

![screen shot 2015-06-17 at 8 31 46 am](https://cloud.githubusercontent.com/assets/238208/8211345/54105b88-14cb-11e5-8552-ab30bac7148b.png)

In 0.5, `<core-component-page sources='["paper-tabs.html", "paper-tab.html"]'>` worked for this.

**Comment by atotic** [comment]
We should support useBowerJson property that parses main.

**Comment by MeTaNoV** [comment]
+1

**Comment by ronnyroeller** [comment]
+1

**Comment by notwaldorf** [comment]
I think you can use an array for the sources in `iron-component-page` now: https://github.com/PolymerElements/paper-tabs/blob/master/index.html#L22

**Comment by ronnyroeller** [comment]
@notwaldorf Using the `sources` property isn't a documented feature and I can't find anything in the source code of `iron-component-page` that it should exists. At least for me it doesn't work.

See https://elements.polymer-project.org/elements/iron-component-page

**Comment by juriejan** [comment]
I also can't get this to work. Also can't find anything in the source code that suggests that it should.

**Comment by notwaldorf** [comment]
paging @garlicnation @justinfagnani @FredKSchott who might know more about how that works
