### ISSUE TITLE
Hydrolysis errors if using ES6 classes

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/iron-component-page#35]
I recently tried using an ES6 class for my element's definition and saw the following hydrolysis error when viewing the docs.

```
Failed to load source at: http://localhost:8080/components/quick-alert/quick-alert.html TypeError: Cannot read property 'forEach' of undefined
    at annotateElement (http://localhost:8080/components/hydrolysis/hydrolysis.js:1061:24)
    at Array.forEach (native)
    at Analyzer.annotate (http://localhost:8080/components/hydrolysis/hydrolysis.js:470:17)
    at http://localhost:8080/components/hydrolysis/hydrolysis.js:177:16
```

I'm wondering if [this PR](https://github.com/Polymer/hydrolysis/pull/127) should fix the issue or if it still requires more work. cc @garlicnation 

Element definition is here if you want to repro:

```html
<link rel="import" href="../polymer/polymer.html">

<!--
An element providing a solution to no problem in particular.
Example:
    <quick-alert></quick-alert>
@group Seed Elements
@element quick-alert
@demo demo/index.html
@hero hero.svg
-->
<dom-module id="quick-alert">
  <style>
    :host {
      display: block;
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
    }
    .alert {
      background-color: #4CAF50;
      color: white;
      padding: 16px;
      font-family: Roboto, Helvetica, sans-serif;
    }
    [hidden] {
      display: none;
    }
  </style>
  <template>
    <div class="alert" hidden="{{!shown}}">
      <content></content>
    </div>
  </template>
</dom-module>

<script>
  'use strict';

  class QuickAlert {
    get is() {
      return 'quick-alert';
    }

    get properties() {
      return {
        shown: {
          type: Boolean,
          value: false
        }
      }
    }
  }

  Polymer(QuickAlert.prototype);
</script>
```

**Comment by cadwmaster** [comment]
Had the same error trying to fix the documentation and demo of the paper-dropdown-menu component

**Comment by bedeoverend** [comment]
+1. Though I'm using a slightly different syntax, the one outlined in [this article](https://www.polymer-project.org/1.0/articles/es6.html) - I'm not sure if that makes a difference to the parser.

**Comment by ebidel** [comment]
Yea, I wouldn't use the syntax in https://github.com/PolymerElements/iron-component-page/issues/35#issue-89300940. `get properties()` is returning a new properties object on every access! Instead, properties should be setup once at registration time. The syntax in the article is :moneybag:

**Comment by cayblood** [comment]
I'm declaring properties in beforeRegister() but still seeing this error. Anyone got this working?

**Comment by bedeoverend** [comment]
Is there any update on this? Did [the ES6 PR](https://github.com/Polymer/hydrolysis/pull/127) attempt to resolve? 

I'm using ES6 in all my components and would love to be able to auto-generate docs, are there any examples / docs of ES6 syntax that is supported by hydrolysis?

**Comment by jgautheron** [comment]
The [ES6 PR](https://github.com/Polymer/hydrolysis/pull/127) didn't solve this issue. I have the same error as @robdodson mentioned above: `Cannot read property 'forEach' of undefined` which is related to the element `properties` not being properly parsed.

This error is only a symptom, not the source of the issue, a quick fix silences the error but still the component page won't show at all.

Here's a sample code which fails:
```javascript
class Foo {
  beforeRegister() {
    this.is = 'foo';
    this.properties = {
      cover: String,
      photo: String,
      username: String
    };
  }
}
Polymer(Foo);
```

Compiling the ES6 code through Babel doesn't help at all. Still fails, for the same reason.

**Comment by jgautheron** [comment]
I fixed it on my [fork](https://github.com/jgautheron/hydrolysis/commit/3ed931c16b9db70d2ebeb95f40889e6562b8ee84).
ES6 class parsing is just not implemented, so I implemented it quickly. I would have thrown a PR, but some tests are failing for no apparent reason and it could be cleaner (a separate `elementFinder` for ES6 classes). If someone is willing to help...

**Comment by efeminella** [comment]
Any ETA or a roadmap for when ES6 class parsing will be natively supported by Hydrolysis, perhaps a PR from @jgautheron 's fork to get this going?

**Comment by jgautheron** [comment]
Just sent a PR:
https://github.com/Polymer/hydrolysis/pull/204

**Comment by RoXuS** [comment]
Hi jgautheron,

Thx for your PR.

It seems to be not good with behavior : 
```
get behaviors() {
    return [
      ...,
    ];
```
The result :
<img width="773" alt="capture d ecran 2015-12-03 a 09 29 49" src="https://cloud.githubusercontent.com/assets/3296671/11555422/705e641a-99a0-11e5-8c8f-f2dd51d20b52.png">

Maybe my statement isn't good ?

**Comment by jgautheron** [comment]
You should declare them in `beforeRegister` with `this.behaviors = [];`.

**Comment by MeTaNoV** [comment]
and for listeners, this should work?
```
this.listeners = {
        'tap': 'regularTap',
        'special.tap': 'specialTap'
      };
```

**Comment by jgautheron** [comment]
Listeners are not shown in the `iron-component-page`, AFAIK for now only the following are displayed:
- properties
- methods
- behaviors
- events

**Comment by efeminella** [comment]
Hey guys, any traction on this yet?

**Comment by justinfagnani** [comment]
I'm moving this bug to hydrolysis

**Comment by mbana** [comment]
Does this actually work now? If so, would someone please post an example. I've been trying to get it to work not realising it's a bug: the /demo/ and /test/ routes in polyserve work, the documentation page however doesn't.

**Comment by justinfagnani** [comment]
@mbana this mug is closed. You can continue the discussion at: https://github.com/Polymer/hydrolysis/issues/221
