### ISSUE TITLE
paper-responsive-change event name cut off in documentation

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-component-page#36]
Moved from https://github.com/PolymerElements/paper-drawer-panel/issues/64

In the [documentation page for `paper-drawer-panel`](https://elements.polymer-project.org/elements/paper-drawer-panel), the name of the `paper-responsive-change` event title is cut off, and appears to be `paper-responsive-`.  

I believe this is because the description of the event does not flow onto multiple lines.  Note the top of the "h" is peaking out from the next line.

![screen shot 2015-06-14 at 10 16 29 pm](https://cloud.githubusercontent.com/assets/2433509/8153504/913ee504-12e3-11e5-844d-426fa4906fce.png)

**Comment by atotic** [comment]
This is because iron-doc-viewer is using absolute layout instead of flow.

Why am I being assigned this? Am I the new owner?

**Comment by blasten** [comment]
@atotic oh sorry. I thought that you were actively contributing to this element.

**Comment by atotic** [comment]
I was, then it was @mbleigh
not sure what's happening right now

**Comment by notwaldorf** [comment]
Duplicate: https://github.com/PolymerElements/iron-doc-viewer/issues/45
