### ISSUE TITLE
Demo button tries to get currentUrl/https

### ISSUE THREAD

**Issue by eudes** [PolymerElements/iron-component-page#37]
After following the reusable elements guide and publishing the repo, I can't get the demo button on the component page to show the demo page. It tries to load the current url + https.

This the component page:
http://eudes.github.io/ph-animated-text-ticker/components/ph-animated-text-ticker/
When the demo button is pressed, it tries to get (and fails) 
http://eudes.github.io/ph-animated-text-ticker/components/ph-animated-text-ticker/https

It doesn't work on local with polyserve either.

**Comment by eudes** [comment]
My bad. I was reusing the doc from the previous version pointing to another user's component page in the @demo tag.

**Comment by LM450N** [comment]
Thank you for yourself answer @eudes, it saved me too ! :wink:
