### ISSUE TITLE
Styles look funky for params on seed-element

### ISSUE THREAD

**Issue by bmcorser** [PolymerElements/iron-component-page#49]
When following [the docs](https://www.polymer-project.org/0.5/docs/start/reusableelements.html) to generate a component page for [`seed-element`](https://github.com/PolymerElements/seed-element), the styles seem to fall apart.

I can fix by changing a margin defined in `iron-component-page` (shown in dodgy gif video below), but I don't see the issue on the [official `seed-element` component page](http://polymerelements.github.io/seed-element/components/seed-element/#methods). The issue can be seen live on the component page of [my clone of `seed-element`](http://porygon.github.io/seed-element/components/seed-element/).

### Chrome
![iron-component-page](https://cloud.githubusercontent.com/assets/1449387/9384047/537ef0b0-4745-11e5-857a-7c80c966ce7a.gif)

### Firefox
![iron-component-page-ff](https://cloud.githubusercontent.com/assets/1449387/9384046/5379a7c2-4745-11e5-8168-fcff0e443cb6.gif)

**Comment by notwaldorf** [comment]
I think the docs styles have changed since this was opened (I don't see any grey anywhere on the docs anymore)
