### ISSUE TITLE
Rewrite this entire element

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-component-page#57]

**Comment by samccone** [comment]
context? :)

**Comment by notwaldorf** [comment]
@samccone well, checking the PRs: https://github.com/PolymerElements/iron-component-page/pull/56#issuecomment-147504281 :smile:

**Comment by samccone** [comment]
:tada: :)

**Comment by atotic** [comment]
Are you soliciting pull requests here?

**Comment by blasten** [comment]
Potentially. The two major goals are:
1. decouple it from the catalog
2. have test in place

**Comment by aomarks** [comment]
We just published iron-component-page 3.0. It was a rewrite. It's decoupled from the catalog (the catalog is gone anyway), and it's got some tests.
