### ISSUE TITLE
Support multiple `demo`'s

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/iron-component-page#67]
For one the element catalog already supports this, and it kind of sucks that 'we normal people' have to list to an ugly `index.html` instead of a beautiful menu xD

(Looked around and can't find an issue for this, if there is one then I apologize)

**Comment by MeTaNoV** [comment]
+1

**Comment by MeTaNoV** [comment]
should be related to https://github.com/PolymerElements/iron-component-page/issues/20

**Comment by aomarks** [comment]
Duplicate of https://github.com/PolymerElements/iron-component-page/issues/67
