### ISSUE TITLE
Properties that take functions as input should still be listed as properties, not methods

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/iron-component-page#77]
Per title, right now a property of `type: Function` ends up in the 'methods' section which is mightily confusing to element consumers. Examples:
- http://polymer.github.io/polymer/ and then the `dom-repeat` (can't link directly)
- http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/api.html?datatable (so have a direct link here)

**Comment by arthurevans** [comment]
dom-repeat.filter is an example:

https://www.polymer-project.org/1.0/api/#dom-repeat:method-filter

Still happening. I'd argue this is more a bug that an enhancement.

**Comment by arthurevans** [comment]
This is fixed in the latest version of `iron-doc-viewer`, closing.

https://www.polymer-project.org/2.0/docs/api/elements/Polymer.DomRepeat#property-filter
