### ISSUE TITLE
Request: Generate event description automatically for properties with notify: true

### ISSUE THREAD

**Issue by Saulis** [PolymerElements/iron-component-page#87]
Especially for users unfamiliar or new to Polymer, it's not usually clear that the small `notifies` notation on the property actually means firing a `*-changed` event. 

Generating event descriptions in the `Events` section automatically for these events would drastically improve the readability of the API for users.

**Comment by justinfagnani** [comment]
@garlicnation is this something we want down in Hydrolysis?

**Comment by garlicnation** [comment]
Yeah! We should add these events in the final annotation pass, before mixing in properties/events from behaviors.

**Comment by justinfagnani** [comment]
Closing in favor of https://github.com/PolymerElements/iron-doc-viewer/issues/67
