### ISSUE TITLE
API Docs: Change section Listbox to visible navigation

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/iron-component-page#96]
_From @kbenjamin on March 16, 2016 19:22_

Until Polycasts 43, I hadn't realized there was more than one section in the [API docs](https://www.polymer-project.org/1.0/api/). 

Please put some simpler navigation in place than a pull-down listbox. Simple links would be fine as there are only 8 choices.

At minimum, please style the listbox such that there is more than a small triangle as evidence that there might be more choices. Colors, borders, something!

_Copied from original issue: Polymer/docs#1585_

**Comment by aomarks** [comment]
3.0 is now published with a full height nav bar.
